name: oligograph
channels:
  - bioconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py39heb7d2ae_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.7.22=h96bc93b_2
  - aws-c-cal=0.6.14=h88a6e22_1
  - aws-c-common=0.9.19=h4ab18f5_0
  - aws-c-compression=0.2.18=h83b837d_6
  - aws-c-event-stream=0.4.2=ha47c788_12
  - aws-c-http=0.8.1=h29d6fba_17
  - aws-c-io=0.14.8=h21d4f22_5
  - aws-c-mqtt=0.10.4=h759edc4_4
  - aws-c-s3=0.5.9=h594631b_3
  - aws-c-sdkutils=0.1.16=h83b837d_2
  - aws-checksums=0.1.18=h83b837d_6
  - aws-crt-cpp=0.26.9=he3a8b3b_0
  - aws-sdk-cpp=1.11.329=hba8bd5f_3
  - beautifulsoup4=4.13.4=pyha770c72_0
  - biopython=1.85=py39h8cd3c5a_1
  - blas=1.0=mkl
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.0.9=py39h5a03fae_8
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=h5008d03_3
  - dill=0.3.7=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.19.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.1=py39heb7d2ae_0
  - forgi=2.1.1=py39hf662ef1_4
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.7.0=py39h53edacf_0
  - fsspec=2023.10.0=pyhca7485f_0
  - future=1.0.0=pyhd8ed1ab_2
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gflags=2.2.2=h5888daf_1005
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py39h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.24.4=h9ad1361_0
  - gstreamer=1.24.4=haf2f30d_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=9.0.0=hfac3d4d_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=py39h06a4308_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_he02047a_1
  - libarrow=16.1.0=hcb6531f_6_cpu
  - libarrow-acero=16.1.0=hac33072_6_cpu
  - libarrow-dataset=16.1.0=hac33072_6_cpu
  - libarrow-substrait=16.1.0=h7e0c224_6_cpu
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=20.1.8=default_ha444ac7_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.10.19=0
  - libcurl=8.8.0=hca28451_1
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libglib=2.80.2=hf974151_0
  - libgomp=15.1.0=h767d61c_5
  - libgoogle-cloud=2.24.0=h2736e30_0
  - libgoogle-cloud-storage=2.24.0=h3d9a0c8_0
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm20=20.1.8=h465586c_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=hd0c01bc_1
  - libopus=1.5.2=hd0c01bc_0
  - libparquet=16.1.0=h6a7eafb_6_cpu
  - libpng=1.6.43=h2797004_0
  - libpq=16.10=h1cdf469_1
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libsystemd0=256.9=h2774228_0
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h54a6638_2
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - logging_exceptions=0.1.8=py_0
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=3.0.2=py39h5eee18b_0
  - matplotlib=3.8.0=py39hf3d152e_2
  - matplotlib-base=3.8.0=py39he9076e7_2
  - mkl=2023.1.0=h213fc3f_46344
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=py39h06a4308_0
  - multidict=6.6.3=py39h9399b63_0
  - multiprocess=0.70.15=py39hd1e30aa_1
  - munkres=1.0.7=py_1
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - ncurses=6.5=h2d0b736_3
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=pyhd8ed1ab_0
  - nspr=4.37=h29cc59b_0
  - nss=3.100=hca3bf56_0
  - numpy=1.26.2=py39h474f0d3_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.5.2=h26f9b46_0
  - orc=2.0.1=h17fec99_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.1.3=py39hddac248_0
  - pcre2=10.43=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - pillow=10.3.0=py39h90c7501_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - ply=3.11=pyhd8ed1ab_3
  - propcache=0.3.1=py39h9399b63_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio-client=17.0=hb77b528_0
  - pyarrow=16.1.0=py39h8003fee_1
  - pyarrow-core=16.1.0=py39h176f5a7_1_cpu
  - pyarrow-hotfix=0.7=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=5.15.9=py39h52134e7_5
  - pyqt5-sip=12.12.2=py39h3d6467e_5
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.18=h0755675_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py39h8cd3c5a_2
  - python_abi=3.9=8_cp39
  - pytorch=2.4.1=py3.9_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h9399b63_2
  - qt-main=5.15.8=hc9dc06e_21
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8c095d6_2
  - regex=2025.7.34=py39hd399759_0
  - requests=2.32.5=pyhd8ed1ab_0
  - s2n=1.4.15=he19d79f_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - safetensors=0.6.2=py39h2bddf42_0
  - scikit-learn=1.3.0=py39hc236052_0
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.7.12=py39h3d6467e_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - soupsieve=2.7=pyhd8ed1ab_0
  - sympy=1.14.0=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - torchaudio=2.4.1=py39_cu121
  - torchtriton=3.0.0=py39
  - torchvision=0.19.1=py39_cu121
  - tornado=6.5.2=py39hd399759_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.35.2=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xxhash=0.8.3=hb47aa4a_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - yarl=1.20.1=py39h9399b63_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - accelerate==1.10.1
      - chanfig==0.0.112
      - danling==0.3.13
      - datasets==4.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.1.9
      - huggingface-hub==0.34.4
      - lazy-imports==1.0.1
      - lightning-utilities==0.15.2
      - multimolecule==0.0.8
      - psutil==7.1.0
      - ptflops==0.7.5
      - pykan==0.2.8
      - seaborn==0.13.2
      - smmap==5.0.2
      - strenum==0.4.15
      - tokenizers==0.15.2
      - torch-geometric==2.6.1
      - torcheval==0.0.7
      - torchmetrics==1.8.2
      - viennarna==2.7.0
prefix: /home/oligoformer/.conda/envs/georna
